### PR TITLE
Toolbar item image changes based on extension mode change

### LINKED ISSUE #29: Indicate when the extension is on/off
Presently, we can stop the extension by clicking on `Stop Injecting`. However, to denote the running state of the extension, there is no on/off visual.
In Safari extensions, we cannot have a modal button so the best thing to do in my opinion, is to have 2 different images, one with the on and one with the off text. Once the `Stop Injecting` is pressed, the image with the off text will be shown as the image of the toolbar item. On clicking `Start Injecting`, the image of the toolbar will be change again.
@smcgregor What do you think about this approach?

### PR DESCRIPTION
**Pull request by sammyshj**
@smcgregor The toolbar item image now changes based on the extension mode change(on/off)
The changes made in this PR are:
* Changed default icon to be shown as toolbar item image.
* Added icons which denote whether extension is on/off
* On changing the mode of the extension(on/off), the toolbar item image changes

**Note:** The icons added look different from that in the Chrome extension. This is because, Safari extension allows only button contents to be filled in black colour. More about this can be read from https://developer.apple.com/library/safari/documentation/Tools/Conceptual/SafariExtensionGuide/AddingButtonstotheMainSafariToolbar/AddingButtonstotheMainSafariToolbar.html

Fixes #29

### CODE REVIEW

**Comment by smcgregor** [comment]
Do they allow shades of gray? We could potentially lighten the color when it is deactivated.

**Comment by sammyshj** [comment]
I did try changing the icon to different shades of gray but, on the Safari toolbar, they appear to be of the same colour. So, we need to have a black image with a transparent background. Let me know if the current icons in the PR are okay.

**Comment by smcgregor** [comment]
How do these look in the browser? I think the text might not look great. How about trying to illustrate it symbolically? Maybe use the [check mark and the "x"](http://getbootstrap.com/components/) in the center of the lock icon in white/transparent?

**Comment by sammyshj** [comment]
@smcgregor Thanks for that! I have changed the icons and they look much better and clearer now in the browser. I have squashed the commits so that the PR can be merged. The look of the icons in the browser can be seen below:
screen shot 2015-07-10 at 1 30 18 am
screen shot 2015-07-10 at 1 30 27 am

**Pull request merged**
