### PR TITLE
Added documentation on javascript background scripts

### PR DESCRIPTION
**Pull request by sammyshj**
Changes made in the PR:
* Added documentation that are built on the javascript background scripts.
* Added jsdoc-toolkit directory that helps in building and storing the background scripts documentation
* The docs have been built using, `java -jar jsrun.jar app/run.js -a -p -t=templates/jsdoc ../../privly.safariextension/scripts/background_scripts/*.*`
* The built docs are stored in `jsdoc-toolkit/out/jsdoc/symbols` directory
* Some basic changes have been made to the jsdoc-toolkit directory so that none of the links break

The changes can be seen at: http://privly-safari.readthedocs.org/en/latest/#privly-safari-extension-package

### CODE REVIEW

**Comment by smcgregor** [comment]
There are a ton of additions here. Do they all need to be in the repo?

**Comment by sammyshj** [comment]
How about I generate the html files locally and only add the html files to the repo rather than having to add the jsdoc-toolkit also?

**Comment by smcgregor** [comment]
Sure, and include instructions for installing/generating docs?

**Comment by sammyshj** [comment]
@smcgregor Added the documentation.rst which contains instructions on how to build the documentation. Added the other html files that are generated from the js files.

**Comment by smcgregor** [comment]
Does ReadTheDocs generate the files or pull in the pre-generated files? If ReadTheDocs generates the files for us, I would prefer to not have them in the source tree.

**Comment by sammyshj** [comment]
ReadTheDocs runs the makes the html files from the rst files. However, the html files that are generated from the javascript files are done directly using the jsdoc-toolkit. So, either we need to add these html files in the source tree, or have the whole jsdoc-toolkit in the source tree and each time build the html files when something is pushed to master.

**Comment by smcgregor** [comment]
OK, let's either exclude the docs when we package the extension for users or include the jsdoc-toolkit as a git submodule.

**Comment by sammyshj** [comment]
Okay, I think its better to exclude the docs then while packaging the extension. The existing docs should work out well.

**Pull request merged**
