### PR TITLE
Added README to the docs

### PR DESCRIPTION
**Pull request by sammyshj**
Added README to the docs with the help of a soft link to the original README in the root directory of the repo
The README.md has been converted to README.rst using [pandoc](http://pandoc.org/)

### CODE REVIEW

**Comment by smcgregor** [comment]
rst is required by readthedocs? It can't use md?

**Comment by sammyshj** [comment]
@smcgregor I checked the conf.py for the sphinx documentation and saw that I can change the  `source_suffix` from only `'.rst'` to `['.rst', '.md']`. However on doing so and generating the html file for the `README.md`, the page does not look rightly formatted. I have attached a screenshot of the page.
screen shot 2015-06-27 at 11 22 12 am
Let me know if you think the change from `.md` to `.rst` is okay, and then, the PR can be merged. Otherwise, I need to make necessary changes to the `README.md` file

**Comment by smcgregor** [comment]
It looks like Read the Docs is not processing the md file into HTML. I am not totally opposed to using rst, but I would prefer not to add another lightweight markup language to the code base if we don't have to.

**Comment by sammyshj** [comment]
@smcgregor Looks like sphinx cannot still parse markdown files properly and, the markdown files need to be converted to rst files to work with sphinx. This is an open issue on the sphinx repo, https://github.com/sphinx-doc/sphinx/issues/825
In the above issue, it is also mentioned by one of the users that the md files can be converted to rst files using pandoc

**Pull request merged**
