### PR TITLE
Opens first run page when the extension is installed

### PR DESCRIPTION
**Pull request by sammyshj**
Open the page `privly-applications/Pages/ChromeFirstRun.html` when the extension is newly installed or when a different version of the extension is installed. The appropriate conditions for the first run page to open are:
1. LocalStorage does not have a stored value for the version of privly installed. (Privly was just installed or localStorage was cleared)
2. The version stored in Info.plist differs from the version stored in localStorage. (Privly was updated)

### CODE REVIEW

**Comment by smcgregor** [comment]
Does the Safari API have anything like Chrome's onInstall or onUpdate events?

**Comment by sammyshj** [comment]
No, the Safari API does not have something like Chrome's onInstall or onUpdate events.
On Safari, we can either use localStorage or add new variables to `safari.extension.settings`.
These can be seen at http://stackoverflow.com/questions/18277602/safari-extension-on-install-event and http://stackoverflow.com/questions/9868985/safari-extension-first-run-and-updates

**Comment by smcgregor** [comment]
OK. Things are going to be changing in storage. Include the local_storage.js script from the shared directory of privly-applications (you can reference it from inside the privly-applications directory) and _only_ store well formed JSON objects to it.

**Comment by sammyshj** [comment]
@smcgregor Updated the code to include local_storage.js of privly-applications and replaced localStorage by ls

**Pull request merged**
